name: HYU-AI Study
description: AI Study group @ Hanyang Univ.
title: tech.blog.HYU-AI
ori_url: 'https://HYUAISTUDY.github.io'
url: 'HYUAISTUDY.github.io'
author: 'Maydev'
permalink: /posts/:title/
type: 'blog'

resume: 'https://github.com/MaybeS/MaybeS.github.io/blob/master/assets/data/resume.pdf?raw=true'
avatar: 'https://avatars0.githubusercontent.com/u/7712538?v=3&s=460'
attach: 'https://raw.githubusercontent.com/MaybeS/MaybeS.github.io/master/assets/images/attach/'
github: 'https://github.com/MaybeS'

paginate: 50
base: /
domain_name: 'https://HYUAISTUDY.github.io'
google_analytics: ''
disqus_shortname: 'hyuai'

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-sitemap
  
future: true
fbcomments: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post